Cross-compile liboqs and OQS-OpenSSL on Linux for Windows as part of OpenVPN build
Only build 64-bit version of OpenVPN because liboqs no longer supports 32-bit build and isn't likely to do so.

diff --git a/windows-nsis/build b/windows-nsis/build
--- a/windows-nsis/build
+++ b/windows-nsis/build
@@ -4,7 +4,6 @@ MAKENSIS="${MAKENSIS:-makensis}"
 OSSLSIGNCODE="${OSSLSIGNCODE:-osslsigncode}"
 ROOT="${ROOT:-tmp}"
 OPENVPN_ROOT="${ROOT}/openvpn"
-OPENVPN_ROOT_I686="${ROOT}/i686"
 OPENVPN_ROOT_X86_64="${ROOT}/x86_64"
 EASYRSA_ROOT="${ROOT}/easy-rsa"
 
@@ -44,10 +43,8 @@ layout() {
 	mkdir "${ROOT}"
 	mkdir "${OPENVPN_ROOT}"
 
-	mkdir "${OPENVPN_ROOT_I686}"
 	mkdir "${OPENVPN_ROOT_X86_64}"
 
-	tar -C "${OPENVPN_ROOT_I686}" -xf "${OPENVPN_TARBALL_I686}" || die "extract openvpn: ${OPENVPN_TARBALL_I686}"
 	tar -C "${OPENVPN_ROOT_X86_64}" -xf "${OPENVPN_TARBALL_X86_64}" || die "extract openvpn: ${OPENVPN_TARBALL_X86_64}"
 
 	if [ -n "${EASYRSA_TARBALL}" ]; then
@@ -72,7 +69,7 @@ sign() {
 main() {
 	layout
 
-	. "${OPENVPN_ROOT_I686}/version.sh" || die "cannot find openvpn version.sh"
+	. "${OPENVPN_ROOT_X86_64}/version.sh" || die "cannot find openvpn version.sh"
 
 	text
 	sign
@@ -80,8 +77,8 @@ main() {
 	mkdir -p ${OPENVPN_ROOT}/share/doc/openvpn/
 
 	cat \
-		"${OPENVPN_ROOT_I686}/share/doc/openvpn/COPYING" \
-		"${OPENVPN_ROOT_I686}/share/doc/openvpn/COPYRIGHT.GPL" \
+		"${OPENVPN_ROOT_X86_64}/share/doc/openvpn/COPYING" \
+		"${OPENVPN_ROOT_X86_64}/share/doc/openvpn/COPYRIGHT.GPL" \
 		> "${OPENVPN_ROOT}/share/doc/openvpn/license.txt" || die "license.txt"
 	
 	VERSION_STRING="${OPENVPN_PACKAGE_VERSION}-I${INSTALLER_VERSION}${INSTALLER_SUFFIX}"
@@ -93,7 +90,6 @@ main() {
 		-DVERSION_STRING="${VERSION_STRING}" \
 		-DSPECIAL_BUILD="${SPECIAL_BUILD}" \
 		-DOPENVPN_ROOT="$(dospath "${OPENVPN_ROOT}")" \
-		-DOPENVPN_ROOT_I686="$(dospath "${OPENVPN_ROOT_I686}")" \
 		-DOPENVPN_ROOT_X86_64="$(dospath "${OPENVPN_ROOT_X86_64}")" \
 		-DTAP_WINDOWS_INSTALLER="$(dospath "${TAP_WINDOWS_INSTALLER}")" \
 		${TAP_WINDOWS_INSTALLER:+-DUSE_TAP_WINDOWS} \
@@ -158,7 +154,6 @@ while [ -n "$1" ]; do
 Usage: $0
 	--installer-version=version     installer version
 	--special-build=string	        special build string
-	--openvpn-bin-tarball-i686=tarball	openvpn binary tarball
 	--openvpn-bin-tarball-x86_64=tarball	openvpn binary tarball
 	--easy-rsa-tarball=tarball	easy-rsa source tarball
 	--tap-windows=installer         tap-windows installer
@@ -176,9 +171,7 @@ __EOF__
 	shift
 done
 
-[ -n "${OPENVPN_TARBALL_I686}" ] || die "please specify openvpn binary tarball"
 [ -n "${OPENVPN_TARBALL_X86_64}" ] || die "please specify openvpn binary tarball"
-[ -f "${OPENVPN_TARBALL_I686}" ] || die "cannot find openvpn binary tarball '${OPENVPN_TARBALL_I686}'"
 [ -f "${OPENVPN_TARBALL_X86_64}" ] || die "cannot find openvpn binary tarball '${OPENVPN_TARBALL_X86_64}'"
 [ -f "${OPENVPNSERV2_EXECUTABLE}" ] || die "cannot find openvpnserv2 executable '${OPENVPNSERV2_EXECUTABLE}'"
 if [ -n "${EASYRSA_TARBALL}" ]; then
